version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_NAME=impera-bot
      - DB_APP_USER=impera-bot
      - DB_APP_PASS=impera-bot
    volumes:
      - "./data:/var/data/db"