name: Java Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ACCESS_TOKEN}}
      - name: Push to deploy
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout -b deploy || true
          git add --force target/*.jar
          git commit -am "Automated: prepare deployment" 
          git push --force --set-upstream origin deploy