name: Java Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          IMPERA_USER_NAME: ${{ secrets.IMPERA_USER_NAME }}
          IMPERA_USER_PASSWORD: ${{ secrets.IMPERA_USER_NAME }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: mvn --batch-mode --update-snapshots package -Dspring.profiles.active=test
      - name: Push to deploy
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git fetch
          git checkout -b deploy || true
          git add --force target/*.jar
          git commit -am "Automated: prepare deployment" 
          git push --force --set-upstream origin deploy